name: flutter_zhihu
description: a zhihu app by flutter

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^1.0.13
  cached_network_image: ^2.1.0+1
  carousel_slider: ^1.0.1
  flutter_webview_plugin: ^0.3.0+2
  share: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/
    - mock/
